#' Install all packages required
#' Only run once
install.packages("caret")
install.packages("mlbench")
install.packages("mvtnorm")
install.packages("kernlab")
install.packages("MASS")
install.packages("MLmetrics")
install.packages("Matrix")
install.packages("plyr")
install.packages("progress")
install.packages("readxl")
install.packages("writexl")
install.packages("doParallel")
install.packages("shiny")
install.packages("dplyr")
install.packages("plotly")
install.packages("shinydashboard")
install.packages("tidyr")
install.packages("microbenchmark")