#' Install all packages required
#' Only run if not
#install.packages("caret")
#install.packages("mlbench")
#install.packages("mvtnorm")
#install.packages("kernlab")
#install.packages("MASS")
#install.packages("MLmetrics")
#install.packages("Matrix")
#install.packages("plyr")
#install.packages("progress")
#install.packages("readxl")
#install.packages("writexl")
#install.packages("doParallel")

library(caret)
library(mlbench)
library(mvtnorm)
library(kernlab)
library(MASS)
library(MLmetrics)
library(Matrix)
library(plyr)
library(progress)
library(readxl)
library(writexl)
library(doParallel)