#Loads all required packages for the simulation
library(caret)
library(kernlab)
library(MASS)
library(MLmetrics)
library(Matrix)
library(plyr)
library(progress)
library(readxl)
library(writexl)
library(doParallel)
library(dplyr)
library(microbenchmark)